services:
  rails:
    container_name: rails-example
    restart: always
    build: .
    command: "rm -f ./tmp/pids/server.pid && ./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production