services:
  rails:
    container_name: rails-example
    restart: always
    build: .
    command: "./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - 80:3000
    environment:
      RAILS_ENV: production